# Generated by Django 4.1 on 2023-09-27 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        help_text="format: required, max:50",
                        max_length=50,
                        unique=True,
                        verbose_name="License Number",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
            },
        ),
        migrations.CreateModel(
            name="CarRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.TextField(
                        help_text="format: required", verbose_name="Route"
                    ),
                ),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
            },
        ),
        migrations.CreateModel(
            name="OwnerCarPark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="format: required, max:100",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="format: required, max:100",
                        max_length=100,
                        verbose_name="Surname",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="format: required, max:100",
                        max_length=100,
                        verbose_name="Lastname",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="format: required, max:100",
                        max_length=12,
                        verbose_name="Phone number",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Park Owner",
                "verbose_name_plural": "Car Park Owners",
            },
        ),
        migrations.CreateModel(
            name="CarPark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "park_name",
                    models.CharField(
                        help_text="format: required, max:100",
                        max_length=100,
                        verbose_name="Car Park Name",
                    ),
                ),
                (
                    "total_cars",
                    models.IntegerField(
                        default=0,
                        help_text="format: required, default-0",
                        verbose_name="number/qty of cars",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_park",
                        to="carpark.ownercarpark",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Park",
                "verbose_name_plural": "Car Parks",
            },
        ),
        migrations.CreateModel(
            name="CarDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="format: required, max:100",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="format: required, max:100",
                        max_length=100,
                        verbose_name="Surname",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="format: required, max:100",
                        max_length=100,
                        verbose_name="Lastname",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="format: required, max:100",
                        max_length=12,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "car",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="car",
                        to="carpark.car",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Driver",
                "verbose_name_plural": "Car Driver",
            },
        ),
    ]
